name: e_commerce
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^4.1.1
  flutter_modular: ^5.0.3
  rx_notifier: ^1.1.0
  http: ^0.13.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^2.0.0
  
flutter:
  uses-material-design: true

  assets:
    - assets/img/